export const GET_VACATIONDETAILS = 'GET_VACATIONDETAILS';
export const GET_VACATIONDETAILS_SUCCESS = 'GET_VACATIONDETAILS_SUCCESS';
export const GET_VACATIONDETAILS_ERROR = 'GET_VACATIONDETAILS_ERROR';
