export const GET_CONT_CAPITAL_NAME = 'GET_CONT_CAPITAL_NAME';
export const GET_CONT_CAPITAL_NAME_SUCCESS = 'GET_CONT_CAPITAL_NAME_SUCCESS';
export const GET_CONT_CAPITAL_NAME_ERROR = 'GET_CONT_CAPITAL_NAME_ERROR';
