export const GET_VACATIONS = 'GET_VACATIONS';
export const GET_VACATIONS_SUCCESS = 'GET_VACATIONS_SUCCESS';
export const GET_VACATIONS_ERROR = 'GET_VACATIONS_ERROR';

export const UPDATE_SHOW_DISCOUNTS = 'UPDATE_SHOW_DISCOUNTS';
